<?php
/**
 * Created by PhpStorm.
 * User: jon
 * Date: 2018/10/12
 * Time: 下午5:30
 */

namespace app\index\controller;


use think\Controller;
use think\Facade;

class Base extends Controller
{
   protected function initialize()
   {
       parent::initialize(); // TODO: Change the autogenerated stub
       $controller =request()->controller();
       $res=db('menu')->where('pid','neq',0)->order('sort')->select();

       $footer=db('banner')->where('type',3)->order('sort')->select();
       $sys=db('system')->where('id',1)->find();
       $assign=[
           'controller'=>$this->strtolower($controller),
           'menu'=>$res,
           'sys'=>$sys,
           'footer'=>$footer
       ];
        $this->assign($assign);
   }

}